"""_format_datetime、_safe_getattr函式提取為工具函式

Revision ID: aa7f6842ac0d
Revises: ed53f944c082
Create Date: 2025-08-10 20:57:33.923351

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aa7f6842ac0d'
down_revision: Union[str, Sequence[str], None] = 'ed53f944c082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
