"""schema 資料夾的 user.py、schedules.py 優化

Revision ID: 721428ee321a
Revises: aa7f6842ac0d
Create Date: 2025-08-12 20:35:12.156610

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '721428ee321a'
down_revision: Union[str, Sequence[str], None] = 'aa7f6842ac0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
