"""移除 users 表的 updated_by 欄位

Revision ID: 4e43517f2669
Revises: 02e132afa7f0
Create Date: 2025-08-17 20:42:17.273121

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4e43517f2669'
down_revision: Union[str, Sequence[str], None] = '02e132afa7f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_updated_by'), 'users', type_='foreignkey')
    op.drop_column('users', 'updated_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'updated_by',
            mysql.INTEGER(display_width=10, unsigned=True),
            autoincrement=False,
            nullable=True,
            comment='最後更新的使用者 ID，可為 NULL（表示系統自動更新）',
        ),
    )
    op.create_foreign_key(
        op.f('fk_users_updated_by'),
        'users',
        'users',
        ['updated_by'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###
