"""同步資料庫型別：TIMESTAMP轉DateTime

Revision ID: 040fda16b06b
Revises: c6dd3264fae3
Create Date: 2025-08-09 14:20:02.831216

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "040fda16b06b"
down_revision: Union[str, Sequence[str], None] = "c6dd3264fae3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment("schedules", existing_comment="行程資料表", schema=None)
    op.alter_column(
        "users",
        "created_at",
        existing_type=mysql.TIMESTAMP(),
        type_=sa.DateTime(),
        nullable=True,
        existing_comment="建立時間",
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=mysql.TIMESTAMP(),
        type_=sa.DateTime(),
        nullable=True,
        existing_comment="更新時間",
        existing_server_default=sa.text(
            "CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"
        ),
    )
    op.alter_column(
        "users",
        "deleted_at",
        existing_type=mysql.TIMESTAMP(),
        type_=sa.DateTime(),
        existing_comment="軟刪除標記",
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_deleted_at"), table_name="users")
    op.drop_index(op.f("idx_email"), table_name="users")
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.drop_table_comment("users", existing_comment="使用者資料表", schema=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment("users", "使用者資料表", existing_comment=None, schema=None)
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.create_index(op.f("idx_email"), "users", ["email"], unique=False)
    op.create_index(op.f("idx_deleted_at"), "users", ["deleted_at"], unique=False)
    op.alter_column(
        "users",
        "deleted_at",
        existing_type=sa.DateTime(),
        type_=mysql.TIMESTAMP(),
        existing_comment="軟刪除標記",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=mysql.TIMESTAMP(),
        nullable=False,
        existing_comment="更新時間",
        existing_server_default=sa.text(
            "CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"
        ),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.DateTime(),
        type_=mysql.TIMESTAMP(),
        nullable=False,
        existing_comment="建立時間",
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.create_table_comment(
        "schedules", "行程資料表", existing_comment=None, schema=None
    )
    # ### end Alembic commands ###
