"""[MVP-1] feat(users): add role column

Revision ID: ff37a0caee1d
Revises: acb071f5b7f1
Create Date: 2025-08-09 19:57:45.774082

"""

from typing import Sequence, Union

# import sqlalchemy as sa
# from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ff37a0caee1d'
down_revision: Union[str, Sequence[str], None] = 'acb071f5b7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
