"""Add new indexes

Revision ID: 985e30da6e53
Revises: 4e43517f2669
Create Date: 2025-08-17 23:47:11.037113

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '985e30da6e53'
down_revision: Union[str, Sequence[str], None] = '4e43517f2669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'idx_schedule_giver_date',
        'schedules',
        ['giver_id', 'date', 'start_time'],
        unique=False,
    )
    op.create_index(
        'idx_schedule_giver_time',
        'schedules',
        ['giver_id', 'start_time', 'end_time'],
        unique=False,
    )
    op.create_index('idx_schedule_status', 'schedules', ['status'], unique=False)
    op.create_index(
        'idx_schedule_taker_date',
        'schedules',
        ['taker_id', 'date', 'start_time'],
        unique=False,
    )
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_index('idx_schedule_taker_date', table_name='schedules')
    op.drop_index('idx_schedule_status', table_name='schedules')
    op.drop_index('idx_schedule_giver_time', table_name='schedules')
    op.drop_index('idx_schedule_giver_date', table_name='schedules')
    # ### end Alembic commands ###
