"""新增 created_by created_by_role deleted_by deleted_by_role 欄位到 schedules 表

Revision ID: 02e132afa7f0
Revises: 721428ee321a
Create Date: 2025-08-17 19:52:48.871218

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '02e132afa7f0'
down_revision: Union[str, Sequence[str], None] = '721428ee321a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'schedules',
        sa.Column(
            'created_by',
            mysql.INTEGER(unsigned=True),
            nullable=True,
            comment='建立者的使用者 ID，可為 NULL（表示系統自動建立）',
        ),
    )
    op.add_column(
        'schedules',
        sa.Column(
            'created_by_role',
            sa.Enum('GIVER', 'TAKER', 'SYSTEM', name='userroleenum'),
            nullable=True,
            comment='建立者角色',
        ),
    )
    op.add_column(
        'schedules',
        sa.Column(
            'deleted_by',
            mysql.INTEGER(unsigned=True),
            nullable=True,
            comment='刪除者的使用者 ID，可為 NULL（表示系統自動刪除）',
        ),
    )
    op.add_column(
        'schedules',
        sa.Column(
            'deleted_by_role',
            sa.Enum('GIVER', 'TAKER', 'SYSTEM', name='userroleenum'),
            nullable=True,
            comment='刪除者角色',
        ),
    )
    op.create_foreign_key(
        None, 'schedules', 'users', ['created_by'], ['id'], ondelete='SET NULL'
    )
    op.create_foreign_key(
        None, 'schedules', 'users', ['deleted_by'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_column('schedules', 'deleted_by_role')
    op.drop_column('schedules', 'deleted_by')
    op.drop_column('schedules', 'created_by_role')
    op.drop_column('schedules', 'created_by')
    # ### end Alembic commands ###
